--todo add translation everywhere
--todo use modname instead of "primitive"
local modname = minetest.get_current_modname()
local modpath = minetest.get_modpath(modname)
dofile(modpath .. "/global.lua")
dofile(modpath .. "/knapping.lua")
dofile(modpath .. "/sans.lua")
dofile(modpath .. "/decorations.lua")
dofile(modpath .. "/knapping_recipes.lua")
dofile(modpath .. "/knapping_tools.lua")
dofile(modpath .. "/grass.lua")
dofile(modpath .. "/dirt.lua")
dofile(modpath .. "/hard_trees.lua")
dofile(modpath .. "/campfire.lua")
dofile(modpath .. "/logs.lua")
dofile(modpath .. "/tool_wear.lua")
dofile(modpath .. "/torches.lua")
dofile(modpath .. "/charring.lua")
dofile(modpath .. "/fences.lua")
dofile(modpath .. "/tree_drops.lua")
dofile(modpath .. "/mad_animalia.lua")
dofile(modpath .. "/beds.lua")
dofile(modpath .. "/throw_stack.lua")