--todo add translation everywhere
--todo use modname instead of "primitive"
local modname = minetest.get_current_modname()
local modpath = minetest.get_modpath(modname)
dofile(modpath .. "/scripts/global.lua")
dofile(modpath .. "/scripts/knapping.lua")
dofile(modpath .. "/scripts/sans.lua")
dofile(modpath .. "/scripts/decorations.lua")
dofile(modpath .. "/scripts/knapping_recipes.lua")
dofile(modpath .. "/scripts/knapping_tools.lua")
dofile(modpath .. "/scripts/grass.lua")
dofile(modpath .. "/scripts/dirt.lua")
dofile(modpath .. "/scripts/hard_trees.lua")
dofile(modpath .. "/scripts/campfire.lua")
dofile(modpath .. "/scripts/logs.lua")

dofile(modpath .. "/scripts/tool_wear.lua")

dofile(modpath .. "/scripts/torches.lua")
dofile(modpath .. "/scripts/charring.lua")
dofile(modpath .. "/scripts/fences.lua")
dofile(modpath .. "/scripts/tree_drops.lua")
dofile(modpath .. "/scripts/mad_animalia.lua")
dofile(modpath .. "/scripts/beds.lua")
dofile(modpath .. "/scripts/throw_stack.lua")
minetest.log("logs:" .. dump( minetest.get_all_craft_recipes("primitive:log_pile")))